-- Flyway migration V13: navigation session (start/pause/resume/end + reroute + event log)

CREATE TABLE IF NOT EXISTS t_navigation_session (
  id VARCHAR(36) PRIMARY KEY,
  user_id VARCHAR(64) NULL,

  status VARCHAR(16) NOT NULL, -- ACTIVE/PAUSED/ENDED
  mode VARCHAR(16) NOT NULL,   -- WALK/WHEELCHAIR

  start_lat DOUBLE PRECISION NOT NULL,
  start_lng DOUBLE PRECISION NOT NULL,
  destination_lat DOUBLE PRECISION NOT NULL,
  destination_lng DOUBLE PRECISION NOT NULL,
  destination_name VARCHAR(255) NULL,

  last_lat DOUBLE PRECISION NULL,
  last_lng DOUBLE PRECISION NULL,
  last_location_at TIMESTAMP NULL,

  deviation_count INT NOT NULL DEFAULT 0,
  reroute_count INT NOT NULL DEFAULT 0,

  created_at TIMESTAMP NOT NULL,
  started_at TIMESTAMP NOT NULL,
  ended_at TIMESTAMP NULL,

  -- Latest route snapshot for debugging/replay (stored as JSON string)
  route_json TEXT NULL
);

CREATE INDEX IF NOT EXISTS idx_nav_session_user_created ON t_navigation_session (user_id, created_at);
CREATE INDEX IF NOT EXISTS idx_nav_session_status ON t_navigation_session (status);
CREATE INDEX IF NOT EXISTS idx_nav_session_created ON t_navigation_session (created_at);

CREATE TABLE IF NOT EXISTS t_navigation_session_event (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id VARCHAR(36) NOT NULL,
  event_type VARCHAR(32) NOT NULL,
  created_at TIMESTAMP NOT NULL,
  payload_json TEXT NULL,
  CONSTRAINT fk_nav_event_session FOREIGN KEY (session_id) REFERENCES t_navigation_session (id)
);

CREATE INDEX IF NOT EXISTS idx_nav_event_session_created ON t_navigation_session_event (session_id, created_at);
CREATE INDEX IF NOT EXISTS idx_nav_event_type ON t_navigation_session_event (event_type);

