-- Flyway migration V14: user accessibility profile (routing preference defaults)

CREATE TABLE IF NOT EXISTS t_accessibility_profile (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id VARCHAR(64) NOT NULL UNIQUE,
  mobility_mode VARCHAR(32) NOT NULL DEFAULT 'WALK',
  avoid_stairs BOOLEAN NOT NULL DEFAULT FALSE,
  avoid_slope BOOLEAN NOT NULL DEFAULT FALSE,
  avoid_construction BOOLEAN NOT NULL DEFAULT TRUE,
  max_slope_percent DOUBLE PRECISION NOT NULL DEFAULT 12.0,
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  CONSTRAINT chk_accessibility_profile_mode
    CHECK (mobility_mode IN ('WALK', 'WHEELCHAIR', 'VISUAL_IMPAIRMENT', 'STROLLER')),
  CONSTRAINT chk_accessibility_profile_max_slope
    CHECK (max_slope_percent >= 0 AND max_slope_percent <= 45)
);

CREATE INDEX IF NOT EXISTS idx_accessibility_profile_mode
  ON t_accessibility_profile (mobility_mode);
