-- V16__voice_reminder_policy.sql
-- 语音提醒策略扩展字段

ALTER TABLE t_voice_settings
  ADD COLUMN IF NOT EXISTS pre_turn_m DOUBLE PRECISION NOT NULL DEFAULT 12,
  ADD COLUMN IF NOT EXISTS pre_arrival_m DOUBLE PRECISION NOT NULL DEFAULT 20,
  ADD COLUMN IF NOT EXISTS announce_interval_m DOUBLE PRECISION NOT NULL DEFAULT 20,
  ADD COLUMN IF NOT EXISTS quiet_hours_start VARCHAR(5) NULL,
  ADD COLUMN IF NOT EXISTS quiet_hours_end VARCHAR(5) NULL,
  ADD COLUMN IF NOT EXISTS vibrate_enabled BOOLEAN NOT NULL DEFAULT true;
