-- Flyway migration V1: init schema (PostgreSQL + PostGIS version)

CREATE EXTENSION IF NOT EXISTS postgis;

-- t_node
CREATE TABLE IF NOT EXISTS t_node (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lat DECIMAL(10,7) NOT NULL,
  lng DECIMAL(10,7) NOT NULL,
  level INT DEFAULT 1,
  node_type VARCHAR(32) NOT NULL,
  extra_json TEXT NULL,
  CONSTRAINT uk_node_lat_lng_level UNIQUE (lat, lng, level)
);

CREATE INDEX idx_node_lat ON t_node (lat);
CREATE INDEX idx_node_lng ON t_node (lng);
CREATE INDEX idx_node_level ON t_node (level);

-- t_edge
CREATE TABLE IF NOT EXISTS t_edge (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  from_node_id BIGINT NOT NULL,
  to_node_id BIGINT NOT NULL,
  distance_m DOUBLE PRECISION NOT NULL,
  is_oneway BOOLEAN NOT NULL,
  has_stairs BOOLEAN NOT NULL,
  is_elevator BOOLEAN DEFAULT FALSE,
  slope_level INT NOT NULL,
  is_accessible_default BOOLEAN NOT NULL,
  base_cost DOUBLE PRECISION NOT NULL,
  CONSTRAINT uk_edge_from_to UNIQUE (from_node_id, to_node_id),
  CONSTRAINT fk_edge_from_node FOREIGN KEY (from_node_id) REFERENCES t_node (id),
  CONSTRAINT fk_edge_to_node FOREIGN KEY (to_node_id) REFERENCES t_node (id)
);

CREATE INDEX idx_edge_from ON t_edge (from_node_id);
CREATE INDEX idx_edge_to ON t_edge (to_node_id);

-- t_graph_snapshot
CREATE TABLE IF NOT EXISTS t_graph_snapshot (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version BIGINT NOT NULL,
  label VARCHAR(64) NOT NULL,
  node_count INT NOT NULL,
  edge_count INT NOT NULL,
  quality_score DOUBLE PRECISION NOT NULL,
  created_at TIMESTAMP NOT NULL,
  snapshot_json TEXT NOT NULL
);

CREATE INDEX idx_graph_snapshot_created ON t_graph_snapshot (created_at);
CREATE INDEX idx_graph_snapshot_version ON t_graph_snapshot (version);

-- t_graph_change_request
CREATE TABLE IF NOT EXISTS t_graph_change_request (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kind VARCHAR(16) NOT NULL,
  payload_type VARCHAR(16) NOT NULL,
  status VARCHAR(16) NOT NULL,
  created_at TIMESTAMP NOT NULL,
  created_by VARCHAR(64) NOT NULL,
  submit_note VARCHAR(255) NULL,
  reviewed_at TIMESTAMP NULL,
  reviewed_by VARCHAR(64) NULL,
  review_note VARCHAR(255) NULL,
  applied_at TIMESTAMP NULL,
  node_count INT NOT NULL,
  edge_count INT NOT NULL,
  quality_score DOUBLE PRECISION NOT NULL,
  payload_json TEXT NOT NULL,
  report_json TEXT NULL
);

CREATE INDEX idx_graph_change_created ON t_graph_change_request (created_at);
CREATE INDEX idx_graph_change_status ON t_graph_change_request (status);
CREATE INDEX idx_graph_change_kind ON t_graph_change_request (kind);

-- t_obstacle_report
CREATE TABLE IF NOT EXISTS t_obstacle_report (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  edge_id BIGINT NOT NULL,
  type VARCHAR(32) NOT NULL,
  status VARCHAR(16) NOT NULL,
  reason VARCHAR(512) NULL,
  photo_urls VARCHAR(2000) NULL,
  submitter_lat DOUBLE PRECISION NULL,
  submitter_lng DOUBLE PRECISION NULL,
  submitter_id VARCHAR(64) NULL,
  submitter_name VARCHAR(128) NULL,
  reviewer_id VARCHAR(64) NULL,
  review_note VARCHAR(1000) NULL,
  reviewed_at TIMESTAMP NULL,
  verification_status VARCHAR(32) NULL,
  created_at TIMESTAMP NOT NULL,
  CONSTRAINT fk_obstacle_report_edge FOREIGN KEY (edge_id) REFERENCES t_edge (id)
);

CREATE INDEX idx_obstacle_edge ON t_obstacle_report (edge_id);
CREATE INDEX idx_obstacle_status ON t_obstacle_report (status);
CREATE INDEX idx_obstacle_created ON t_obstacle_report (created_at);

-- t_obstacle_effect
CREATE TABLE IF NOT EXISTS t_obstacle_effect (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  edge_id BIGINT NOT NULL,
  active BOOLEAN NOT NULL,
  disabled BOOLEAN NOT NULL,
  start_at TIMESTAMP NULL,
  end_at TIMESTAMP NULL,
  reason VARCHAR(512) NULL,
  CONSTRAINT fk_obstacle_effect_edge FOREIGN KEY (edge_id) REFERENCES t_edge (id)
);

CREATE UNIQUE INDEX uk_effect_edge_active ON t_obstacle_effect (edge_id, active);
CREATE INDEX idx_effect_edge ON t_obstacle_effect (edge_id);
CREATE INDEX idx_effect_active ON t_obstacle_effect (active);

-- user_accounts
CREATE TABLE IF NOT EXISTS user_accounts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(64) NOT NULL,
  password_hash VARCHAR(120) NOT NULL,
  role VARCHAR(16) NOT NULL,
  created_at TIMESTAMP NOT NULL,
  credit_score INT NULL,
  last_login_at TIMESTAMP NULL,
  CONSTRAINT uk_user_accounts_username UNIQUE (username)
);

-- operation_logs
CREATE TABLE IF NOT EXISTS operation_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor VARCHAR(64) NOT NULL,
  action VARCHAR(64) NOT NULL,
  detail VARCHAR(512) NULL,
  created_at TIMESTAMP NOT NULL
);

CREATE INDEX idx_operation_logs_created_at ON operation_logs (created_at);
CREATE INDEX idx_operation_logs_action ON operation_logs (action);
