-- PR-10: Indoor navigation - building metadata and node-building association
CREATE TABLE IF NOT EXISTS t_building (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(128) NOT NULL,
    code VARCHAR(32),
    min_level INT NOT NULL DEFAULT 1,
    max_level INT NOT NULL DEFAULT 1,
    center_lat DOUBLE PRECISION NOT NULL,
    center_lng DOUBLE PRECISION NOT NULL
);

ALTER TABLE t_node ADD COLUMN IF NOT EXISTS building_id BIGINT REFERENCES t_building(id);
CREATE INDEX IF NOT EXISTS idx_node_building ON t_node (building_id);
