-- PR-15: API Key management for open API / SDK access
CREATE TABLE IF NOT EXISTS t_api_key (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key_id VARCHAR(64) NOT NULL UNIQUE,
  key_secret_hash VARCHAR(128) NOT NULL,
  owner_id VARCHAR(64) NOT NULL,
  tenant_id VARCHAR(32) NOT NULL DEFAULT 'default',
  scopes VARCHAR(512) NOT NULL DEFAULT 'route:read',
  rate_limit_per_minute INT NOT NULL DEFAULT 60,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  last_used_at TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_api_key_key_id ON t_api_key (key_id);
CREATE INDEX IF NOT EXISTS idx_api_key_owner ON t_api_key (owner_id);
CREATE INDEX IF NOT EXISTS idx_api_key_tenant ON t_api_key (tenant_id);
