-- PR-16: Emergency broadcast enhancement - severity levels and zones
ALTER TABLE t_emergency_event ADD COLUMN IF NOT EXISTS severity VARCHAR(16) NOT NULL DEFAULT 'NORMAL';
ALTER TABLE t_emergency_event ADD COLUMN IF NOT EXISTS zone_id BIGINT;
ALTER TABLE t_emergency_event ADD COLUMN IF NOT EXISTS broadcast_radius_m INT NOT NULL DEFAULT 500;

CREATE TABLE IF NOT EXISTS t_emergency_zone (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(128) NOT NULL,
  code VARCHAR(32) UNIQUE,
  center_lat DOUBLE PRECISION NOT NULL,
  center_lng DOUBLE PRECISION NOT NULL,
  radius_m INT NOT NULL DEFAULT 500,
  alert_level VARCHAR(16) NOT NULL DEFAULT 'NORMAL',
  active BOOLEAN NOT NULL DEFAULT TRUE,
  tenant_id VARCHAR(32) NOT NULL DEFAULT 'default',
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_emergency_zone_tenant ON t_emergency_zone (tenant_id);
CREATE INDEX IF NOT EXISTS idx_emergency_event_severity ON t_emergency_event (severity);
