-- Flyway migration V4: create facility tables for accessibility features

-- 无障碍设施表
CREATE TABLE IF NOT EXISTS t_facility (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    facility_type VARCHAR(32) NOT NULL,  -- ELEVATOR, RAMP, ACCESSIBLE_TOILET, BRAILLE_SIGN, AUDIO_SIGNAL, WHEELCHAIR_CHARGING
    name VARCHAR(128),
    description TEXT,
    building_name VARCHAR(128),
    floor_level INT DEFAULT 1,
    lat DECIMAL(10,7) NOT NULL,
    lng DECIMAL(10,7) NOT NULL,
    -- 运营时间 JSON 格式: {"mon": "08:00-22:00", "tue": "08:00-22:00", ...}
    opening_hours TEXT,
    is_operational BOOLEAN DEFAULT true,
    last_verified_at TIMESTAMP,
    verified_by VARCHAR(64),
    photo_url VARCHAR(512),
    contact_info VARCHAR(256),
    notes TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

-- 设施无障碍特性表
CREATE TABLE IF NOT EXISTS t_facility_feature (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    facility_id BIGINT NOT NULL REFERENCES t_facility(id) ON DELETE CASCADE,
    feature_type VARCHAR(32) NOT NULL,  -- WHEELCHAIR_ACCESSIBLE, BRAILLE_SIGN, AUDIO_GUIDE, HANDRAIL, AUTO_DOOR
    feature_value VARCHAR(128),
    notes TEXT
);

-- 设施问题上报表
CREATE TABLE IF NOT EXISTS t_facility_issue (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    facility_id BIGINT NOT NULL REFERENCES t_facility(id) ON DELETE CASCADE,
    issue_type VARCHAR(32) NOT NULL,  -- OUT_OF_SERVICE, NEEDS_REPAIR, INCORRECT_INFO, OTHER
    description TEXT NOT NULL,
    photo_url VARCHAR(512),
    reporter_id VARCHAR(64),
    reporter_name VARCHAR(128),
    status VARCHAR(16) NOT NULL DEFAULT 'PENDING',  -- PENDING, CONFIRMED, RESOLVED, REJECTED
    resolved_at TIMESTAMP,
    resolved_by VARCHAR(64),
    resolve_note TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

-- 索引
CREATE INDEX idx_facility_type ON t_facility(facility_type);
CREATE INDEX idx_facility_location ON t_facility(lat, lng);
CREATE INDEX idx_facility_building ON t_facility(building_name);
CREATE INDEX idx_facility_operational ON t_facility(is_operational);

CREATE INDEX idx_facility_feature_facility ON t_facility_feature(facility_id);
CREATE INDEX idx_facility_feature_type ON t_facility_feature(feature_type);

CREATE INDEX idx_facility_issue_facility ON t_facility_issue(facility_id);
CREATE INDEX idx_facility_issue_status ON t_facility_issue(status);
CREATE INDEX idx_facility_issue_created ON t_facility_issue(created_at);
